name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 23.x
          
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9.15.0
          
      - name: Install dependencies
        run: pnpm install
        
      - name: Build
        run: pnpm build
        
      - name: Lint
        run: pnpm lint
        
      - name: Test
        run: pnpm test
        env:
          NODE_OPTIONS: --max-old-space-size=4096

  integration-tests:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 23.x
          
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9.15.0
          
      - name: Install dependencies
        run: pnpm install
        
      - name: Integration tests
        run: pnpm test:integration
        env:
          RPC_ENDPOINT: ${{ secrets.RPC_ENDPOINT }}
          WALLET_PUBLIC_KEY: ${{ secrets.WALLET_PUBLIC_KEY }}